require("dotenv").config();
const express = require("express");
const app = express();
const bodyParser = require("body-parser");
app.use(bodyParser.json());
const mongoose = require("mongoose");
const cors = require("cors");
app.use(cors());
mongoose.connect(process.env.MONGO_URL, { useNewUrlParser: true });
const db = mongoose.connection;
db.on("error", (error) => console.error(error));
db.once("open", () => console.log("Connected to DataBase"));
const userRouter = require("./Routes/User");
app.use("/api/users", userRouter);
const EquipementRouter = require("./Routes/Equipement");
app.use("/api/Equipement", EquipementRouter);
app.listen(3010, () => console.log("Server Started"));
